#!/usr/bin/env python3
"""Generate data/words.json with 160+ themed entries."""
import json
import random

random.seed(42)

easy = [
    ("cat", ["kitten", "feline"]),
    ("dog", ["puppy", "hound"]),
    ("sun", ["sunshine", "solar"]),
    ("moon", ["lunar"]),
    ("star", ["stellar"]),
    ("cloud", ["sky"]),
    ("rain", ["raindrop"]),
    ("snow", ["snowflake"]),
    ("tree", ["oak"]),
    ("flower", ["blossom", "bloom"]),
    ("leaf", ["foliage"]),
    ("house", ["home", "cottage"]),
    ("car", ["automobile", "vehicle"]),
    ("bus", ["coach"]),
    ("train", ["locomotive"]),
    ("boat", ["ship", "vessel"]),
    ("fish", ["seafood"]),
    ("bird", ["avian"]),
    ("apple", ["fruit"]),
    ("banana", ["fruit"]),
    ("pizza", ["pie"]),
    ("cake", ["dessert"]),
    ("cookie", ["biscuit"]),
    ("book", ["novel", "tome"]),
    ("phone", ["mobile", "cell"]),
    ("chair", ["seat"]),
    ("table", ["desk"]),
    ("clock", ["timepiece"]),
    ("hat", ["cap"]),
    ("shoe", ["sneaker"]),
    ("ball", ["sphere"]),
    ("heart", ["love"]),
    ("smile", ["grin"]),
    ("eye", ["vision"]),
    ("hand", ["palm"]),
    ("foot", ["feet"]),
    ("tooth", ["teeth"]),
    ("bed", ["mattress"]),
    ("door", ["gate"]),
    ("window", ["pane"]),
    ("bridge", ["overpass"]),
    ("mountain", ["peak"]),
    ("river", ["stream"]),
    ("beach", ["shore"]),
    ("island", ["isle"]),
    ("rocket", ["spaceship"]),
    ("robot", ["android"]),
    ("guitar", ["axe"]),
    ("drum", ["percussion"]),
    ("piano", ["keys"]),
    ("umbrella", ["parasol"]),
    ("glasses", ["spectacles"]),
    ("key", ["lock opener"]),
]

medium = [
    ("elephant", ["pachyderm"]),
    ("giraffe", ["tall animal"]),
    ("penguin", ["antarctic bird"]),
    ("octopus", ["cephalopod"]),
    ("butterfly", ["moth"]),
    ("volcano", ["mount eruption"]),
    ("tornado", ["twister"]),
    ("lightning", ["thunder bolt"]),
    ("rainbow", ["spectrum"]),
    ("castle", ["fortress"]),
    ("pyramid", ["tomb"]),
    ("lighthouse", ["beacon"]),
    ("windmill", ["turbine"]),
    ("bicycle", ["bike"]),
    ("motorcycle", ["motorbike"]),
    ("helicopter", ["chopper"]),
    ("airplane", ["aeroplane", "plane"]),
    ("tractor", ["farm vehicle"]),
    ("ambulance", ["ems"]),
    ("firetruck", ["fire engine"]),
    ("telescope", ["scope"]),
    ("microscope", ["magnifier"]),
    ("compass", ["direction tool"]),
    ("backpack", ["rucksack"]),
    ("binoculars", ["field glasses"]),
    ("camera", ["photocamera"]),
    ("microphone", ["mic"]),
    ("headphones", ["earphones"]),
    ("laptop", ["notebook pc"]),
    ("keyboard", ["keys"]),
    ("scissors", ["shears"]),
    ("hammer", ["mallet"]),
    ("wrench", ["spanner"]),
    ("ladder", ["steps"]),
    ("fence", ["railing"]),
    ("crown", ["royal headwear"]),
    ("wizard", ["sorcerer"]),
    ("dragon", ["wyrm"]),
    ("unicorn", ["mythical horse"]),
    ("ghost", ["spirit"]),
    ("vampire", ["dracula"]),
    ("pirate", ["buccaneer"]),
    ("astronaut", ["spacewalker"]),
    ("chef", ["cook"]),
    ("ninja", ["shinobi"]),
    ("cowboy", ["rancher"]),
    ("detective", ["sleuth"]),
    ("jungle", ["rainforest"]),
    ("desert", ["dunes"]),
    ("waterfall", ["cascade"]),
    ("canyon", ["gorge"]),
    ("igloo", ["snow hut"]),
    ("tent", ["shelter"]),
    ("campfire", ["bonfire"]),
    ("snowman", ["frosty"]),
]

hard = [
    ("parachute", ["chute"]),
    ("submarine", ["sub"]),
    ("satellite", ["orbit craft"]),
    ("skyscraper", ["tower"]),
    ("drawbridge", ["bascule"]),
    ("rollercoaster", ["coaster"]),
    ("ferris wheel", ["big wheel"]),
    ("easel", ["artist stand"]),
    ("hourglass", ["sand timer"]),
    ("metronome", ["tempo device"]),
    ("sundial", ["shadow clock"]),
    ("sextant", ["navigation tool"]),
    ("accordion", ["squeezebox"]),
    ("harp", ["lyre"]),
    ("cello", ["string instrument"]),
    ("trombone", ["brass slide"]),
    ("saxophone", ["sax"]),
    ("bagpipes", ["pipes"]),
    ("sphinx", ["statue"]),
    ("obelisk", ["monolith"]),
    ("pagoda", ["temple tower"]),
    ("aqueduct", ["water bridge"]),
    ("wind turbine", ["windmill"]),
    ("dam", ["hydro barrier"]),
    ("crane", ["construction arm"]),
    ("bulldozer", ["dozer"]),
    ("excavator", ["digger"]),
    ("spacesuit", ["eva suit"]),
    ("radio telescope", ["dish"]),
    ("particle collider", ["atom smasher"]),
    ("periscope", ["submarine scope"]),
    ("catapult", ["siege engine"]),
    ("trebuchet", ["sling"]),
    ("alchemy", ["potion making"]),
    ("constellation", ["star pattern"]),
    ("aurora", ["northern lights"]),
    ("tsunami", ["tidal wave"]),
    ("iceberg", ["glacial ice"]),
    ("geyser", ["hot spring"]),
    ("stalactite", ["cave spike"]),
    ("stalagmite", ["cave column"]),
    ("quicksand", ["sink sand"]),
    ("whirlpool", ["eddy"]),
    ("archipelago", ["island chain"]),
    ("peninsula", ["cape"]),
    ("fjord", ["glacial inlet"]),
    ("glacier", ["ice river"]),
    ("savanna", ["grassland"]),
    ("oasis", ["desert spring"]),
    ("mangrove", ["coastal tree"]),
    ("coral reef", ["reef"]),
    ("battleship", ["warship"]),
    ("zeppelin", ["blimp"]),
    ("catamaran", ["twin hull"]),
    ("gondola", ["canal boat"]),
    ("cuckoo clock", ["bird clock"]),
    ("lantern", ["lamp"]),
    ("chandelier", ["ceiling lamp"]),
    ("mannequin", ["display model"]),
    ("maypole", ["dance pole"]),
    ("totem pole", ["totem"]),
    ("kaleidoscope", ["color tube"]),
    ("planetarium", ["star dome"]),
]

def main():
    out = []
    for w, syns in easy:
        out.append({"word": w, "difficulty": 1, "synonyms": syns})
    for w, syns in medium:
        out.append({"word": w, "difficulty": 2, "synonyms": syns})
    for w, syns in hard:
        out.append({"word": w, "difficulty": 3, "synonyms": syns})

    random.shuffle(out)
    path = "../data/words.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
    print(len(out), "words written to", path)


if __name__ == "__main__":
    main()
